version: '3.7' # specify docker-compose version
# Define the services/containers to be run
services:
  frontend: #name of the first service
    build: client # specify the directory of the Dockerfile
    ports:
      - "8080:8080" # specify port forewarding
    volumes:
      - '.:/app'
      - '/app/node_modules'
    restart: always
  backend: #name of the second service
    build: server # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    restart: always